### PR TITLE
Add install definitions

### PR DESCRIPTION
**Pull request by DDRBoxman**
This changes add an install step to cmake that puts the headers and libs in the correct folders. This will enable integration into the obs-deps repo.

### CODE REVIEW

**Comment by DDRBoxman** [comment]
@paulh-aja 
@PatTheMav

**Comment by PatTheMav** [comment]
This line needs to be removed - macOS deployment target for arm64 architecture needs to be 11.0 minimum:

https://github.com/aja-video/ntv2/blob/fe2462254864fb0d6b2838e506fd905cddebfc4f/cmake/BuildConfig.cmake#L5

**Comment by paulh-aja** [comment]
> This line needs to be removed or changed to be architecture-aware - macOS deployment target for arm64 architecture needs to be 11.0 minimum:
> 
> https://github.com/aja-video/ntv2/blob/fe2462254864fb0d6b2838e506fd905cddebfc4f/cmake/BuildConfig.cmake#L5
> 
> (Funnily enough I get a ton of these warnings: `OSAtomicAdd64Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_add() from <atomic> instead`).

NTV2 still supports macOS 10.12 and onward at the moment.
1. When you say change this line to be architecture-aware, could you be more specific with regards to how that is done in CMake?
2. Could the OBS build scripts for macOS just override this variable? Or is there another better way to handle this?
3. Does OBS support the arm64 arch yet? I was under the impression after previous discussions w/ @DDRBoxman that it wasn't quite there yet.

Right now the NTV2 CMake is set up in such a way that each arch needs to be built separately and then, if desired, the outputs could be stitched together into a universal binary w/ the Apple `lipo` tool. This is how AJA currently builds the its applications and libraries internally, using our older `qmake` build system. The CMake scripts are slowly working towards replacing those old scripts but some functionality is not yet implemented yet.

I'd implemented some similar functionality to this PR, to coalesce headers and sources into the build output directory. But it looks like using the CMake `install` command is probably the way to go instead. I am going to push my latest CMake changes for NTV2 to github and take a look at how this PR would integrate with it.

**Comment by PatTheMav** [comment]
You specify `FORCE` in the line I mentioned, so any user defined variable is ignored by CMake (as is the `MACOSX_DEPLOYMENT_TARGET` environment variable that CMake recognises for this purpose). We either set the cache or environment variable to ensure the correct deployment target.

If you want to ensure a lower boundary of 10.12 for macOS builds then you should check the value of `CMAKE_OSX_DEPLOYMENT_TARGET` first and `fatal_error` if it's below that (CMake has version comparators for strings) and otherwise set it to `10.12` without `FORCE`. You _could_ check the value of `CMAKE_OSX_ARCHITECTURES` and set the target to `11.0` for the arm64 architecture, but allowing the user to set it accordingly should be sufficient.

Our dependencies support arm64 since August, so any new dependency would have to as well, especially as it's required to have https://github.com/obsproject/obs-studio/pull/5155 merged (and we'd like to have an official M1 build out sooner rather than later).

> Right now the NTV2 CMake is set up in such a way that each arch needs to be built separately and then, if desired, the outputs could be stitched together into a universal binary w/ the Apple `lipo` tool. This is how AJA currently builds the its applications and libraries internally, using our older `qmake` build system. The CMake scripts are slowly working towards replacing those old scripts but some functionality is not yet implemented yet.

In general it's preferable to have CMake take care of it (if you specify both architectures to CMake it will create universal binaries directly) - obs-deps allows generation of universal builds as well as architecture-specific ones and only uses `lipo` if a dependency doesn't use CMake. On CI we build each architecture separately and use a final job to combine architectures, so both use cases have to be supported.

> I'd implemented some similar functionality to this PR, to coalesce headers and sources into the build output directory. But it looks like using the CMake `install` command is probably the way to go instead. I am going to push my latest CMake changes for NTV2 to github and take a look at how this PR would integrate with it.

Yeah, `cmake --install BUILD_DIR` is the preferred way to create a self-contained package of your library, with the `CMAKE_INSTALL_PREFIX` being the final destination (check the `CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT`variable to see if the current configuration uses a user-specified path or a CMake default). We use this to redirect the installed library to a special directory which we then just package for obs-deps (and also allows us to create a "proper" artifact on CI even with build dirs restored from cache). When building OBS we just have to point CMake to this directory as a prefix and it'll find all the libraries and headers automatically.

**Comment by paulh-aja** [comment]
OK, I am merging these changes now that @DDRBoxman has merged my most recent CMake changes into the PR branch. This should get us going for the initial AJA plugin release in OBS.

**Pull request merged**
